#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########

set -x
set -e

# Cleanup
rm -rf /var/lib/apt/lists/*
apt clean

# Remove useless version info
rm -f /etc/custompios_buildbase
rm -f /etc/${DIST_NAME,,}_version
rm -f /etc/dist_variant
